[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[deploy.volumes]]
mountPath = "/data"
name = "lynx-data"

[env]
NODE_ENV = "production"
PORT = "3000"
DATABASE_URL = "file:/data/lynx.db"

[deploy.healthcheck]
path = "/health"
timeout = 30
